# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import spelling_bee_game_pb2 as spelling__bee__game__pb2


class SpellingBeeGameStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateGame = channel.unary_unary(
                '/app.SpellingBeeGame/CreateGame',
                request_serializer=spelling__bee__game__pb2.GameRequest.SerializeToString,
                response_deserializer=spelling__bee__game__pb2.GameResponse.FromString,
                )
        self.FinalizeGame = channel.unary_unary(
                '/app.SpellingBeeGame/FinalizeGame',
                request_serializer=spelling__bee__game__pb2.FinalizeRequest.SerializeToString,
                response_deserializer=spelling__bee__game__pb2.FinalizeResponse.FromString,
                )
        self.ProcessSuggestion = channel.unary_unary(
                '/app.SpellingBeeGame/ProcessSuggestion',
                request_serializer=spelling__bee__game__pb2.SuggestionRequest.SerializeToString,
                response_deserializer=spelling__bee__game__pb2.SuggestionResponse.FromString,
                )


class SpellingBeeGameServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalizeGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessSuggestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpellingBeeGameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateGame': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGame,
                    request_deserializer=spelling__bee__game__pb2.GameRequest.FromString,
                    response_serializer=spelling__bee__game__pb2.GameResponse.SerializeToString,
            ),
            'FinalizeGame': grpc.unary_unary_rpc_method_handler(
                    servicer.FinalizeGame,
                    request_deserializer=spelling__bee__game__pb2.FinalizeRequest.FromString,
                    response_serializer=spelling__bee__game__pb2.FinalizeResponse.SerializeToString,
            ),
            'ProcessSuggestion': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessSuggestion,
                    request_deserializer=spelling__bee__game__pb2.SuggestionRequest.FromString,
                    response_serializer=spelling__bee__game__pb2.SuggestionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.SpellingBeeGame', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SpellingBeeGame(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/app.SpellingBeeGame/CreateGame',
            spelling__bee__game__pb2.GameRequest.SerializeToString,
            spelling__bee__game__pb2.GameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FinalizeGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/app.SpellingBeeGame/FinalizeGame',
            spelling__bee__game__pb2.FinalizeRequest.SerializeToString,
            spelling__bee__game__pb2.FinalizeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ProcessSuggestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/app.SpellingBeeGame/ProcessSuggestion',
            spelling__bee__game__pb2.SuggestionRequest.SerializeToString,
            spelling__bee__game__pb2.SuggestionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
